[book]
authors = [
    "Luis Silva <luis@teton.ai>",
    "Roland Kajatin <roland@teton.ai>",
    "Alvaro Molina <alvaro@teton.ai>",
    "Christian Bender <cbender@teton.ai>",
]
language = "en"
multilingual = false
src = "src"
title = "Smith Documentation"
